# Test goal: old Clang as host compiler with old CUDA
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   GPU: CUDA oldest supported
#   HW: NVIDIA GPU
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithAssert
#   Compiler: Clang 9
#   GPU: CUDA 11.0
#   MPI: thread_MPI
#   SIMD: AVX_512
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2 (unit tests)
#   Parallelism nt/ntomp: 2/1 (regression tests)

gromacs:clang-9-cuda-11.0:release:configure:
  extends:
    - .gromacs:base:release:configure
    - .use-clang:base
    - .use-cuda
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-9-cuda-11.0.3
  variables:
    COMPILER_MAJOR_VERSION: 9
    RELEASE_BUILD_DIR: release-builds-clang
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX_512"

gromacs:clang-9-cuda-11.0:release:build:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  stage: release-build
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  variables:
    BUILD_DIR: release-builds-clang
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-9-cuda-11.0.3
  needs:
    - job: gromacs:clang-9-cuda-11.0:release:configure

gromacs:clang-9-cuda-11.0:release:test:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:nightly-only-for-release, rules]
  stage: release-tests
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-9-cuda-11.0.3
  variables:
    BUILD_DIR: release-builds-clang
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
    GMX_FORCE_UPDATE_DEFAULT_CPU: 1
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:clang-9-cuda-11.0:release:configure
    - job: gromacs:clang-9-cuda-11.0:release:build

gromacs:clang-9-cuda-11.0:release:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:nightly-only-for-release, rules]
  stage: release-tests
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-9-cuda-11.0.3
  variables:
    BUILD_DIR: release-builds-clang
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:clang-9-cuda-11.0:release:build
    - job: regressiontests:package

